name: Actions Workflow

on:
  # repository_dispatch:
  #   types: [build]
  # schedule:
  # - cron: "0/5 * * * *"
  # - cron: "0/6 * * * *"
  push:
    # branches:
      # - develop
      # - 'features/*' # matches features/featA, features/featB, doesn't match features/feat/A
      # - 'features/**' # matches features/featA, features/featB, features/feat/A
      # - '!features/featC' #ignore this branch
    # branches-ignore:
    # tags:
      # - v1.*
    # tags-ignore:
      # -v2.*
    paths:
      - '**.js'
      - '!filename.js'
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, closed, reopened, assigned]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Ajay
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
